name: running_on_dart
version: 3.0.0-dev.0
description: Discord Bot for nyxx development
homepage: https://github.com/nyxx-discord/running_on_dart
repository: https://github.com/nyxx-discord/running_on_dart
documentation: https://github.com/nyxx-discord/running_on_dart
issue_tracker: https://github.com/nyxx-discord/running_on_dart/issues
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  fuzzy: ^0.4.0-nullsafety.0
  http: ^0.13.4
  human_duration_parser: ^2.0.1
  logging: ^1.0.2
  migent:
    git: https://github.com/nyxx-discord/migent.git
  nyxx: ^3.4.1
  nyxx_commands: ^4.1.2
  nyxx_interactions: ^4.1.0
  nyxx_pagination: ^2.2.0
  postgres: ^2.4.3
  time_ago_provider: ^4.1.2

dev_dependencies: 
  lints: ^1.0.1
