name: running_on_dart
version: 3.0.0-dev.0
description: Discord Bot for nyxx development
homepage: https://github.com/nyxx-discord/running_on_dart
repository: https://github.com/nyxx-discord/running_on_dart
documentation: https://github.com/nyxx-discord/running_on_dart
issue_tracker: https://github.com/nyxx-discord/running_on_dart/issues
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  http: ^0.13.4
  nyxx: ^3.4.1
  nyxx_commands: ^4.1.1

dev_dependencies: 
  lints: ^1.0.1
