name: ci

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest

    env:
      DOCKER_ORG: git.asion.dev
      DOCKER_LATEST: latest
      DOCKER_IMAGE_NAME: ${{ env.DOCKER_ORG }}/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_ORG }}
          username: ${{ github.actor }}
          password: ${{ secrets.RUNNER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME}}
